### PR TITLE
Great changes... help welcome!

### PR DESCRIPTION
**Pull request by SquareBoot**
Hello everyone,
I got interested in IPARCOS and I thought that updating it to make it work correctly with the latest INDI drivers and Android version would be great. At the moment I made the following changes: 
- Full **Italian translation**
- Targeting the latest Android release (API 27)
- Updated to work with the latest Android Studio & Gradle versions
- Material design (still red on a dark background)
- New adaptive & legacy **icon**! Let me know if you like it...
- Updated license and readme
- Completely reformatted code (I know, unuseful, but important)
- Optimization whenever Android Studio suggested it (e.g.: `for` changed in `for each`, string concatenation in loops)

Known issues:
- Unfortunately, after moving to `Appcompat`, the Control Panel isn't able to open anymore. I detected that the problem is related to the management of the `Fragment`s and the tabs. Help is welcome, thanks!

To do:
- Fix `GenericActivity`
- Remove unused resources. I didn't do it because I saw that a settings screen has been planned.
- Object search activity
- If possible, update the INDI4Java drivers sources (?)
- Remove the other branch, since Gradle has been successfully updated.

Moreover, I have to say that even with the latest stable release of IPARCOS, if using an EQMOD mount (AstroEQ in my case) the in-app control panel doesn't open. If, instead, I connect the app to a "telescope simulator", the control panel opens, so there may be a problem with the INDI client, too :confused:
If you are interested, I can collaborate. Feel free to reject the changes you don't like; I apologize for the fact that all the changes were been made using just a few of commits, but auto reformatting changed almost everything.
Kind regards,
SquareBoot

### CODE REVIEW

**Comment by SquareBoot** [comment]
ViewPager fixed, now the GenericActivity works. However, the app sometimes crashes while trying to restore the control panel whenever I move to another activity and then I come back there.
Added scrollbars to the GenericActivity's dialogs.

**Comment by farom57** [comment]
Hi,

I really appreciate your help in IPARCOS. You have proposed great changes and you look very motivated.
I haven't work on IPARCOS for some time now, mainly by lack of time but also because I have less need for this application now. I am relying mainly on Kstars on my PC and Kstars lite on android, I only use IPARCOS as a joystick for my telescope.
I am sorry for the late answer but i don't like to return to my old (dirty) code and it's even worse for the code of someone else. It takes me some time get the motivation. By the way, you are courageous to try to understand my code and I apologize for any dirty things in it.
I need some time to reinstall Android Studio and to look at what you have done but I will try to do it this week.

Kind regards
Farom

**Comment by farom57** [comment]
Nice interface!
I get a android.os.NetworkOnMainThreadException each time a try to change a property. I have found the bug and I am working on a fix

**Comment by SquareBoot** [comment]
Hello,
Thanks for having accepted my pull request! I saw your fix and I modified the `AsyncTask` a bit to avoid static `Context`s. I'm working to add an Activity to manage/remove servers. I've also added an "About" activity and planned to remove unused resources, I'll open a pull request soon. This fork fixes #16 (maybe #17?). What about the `SkyObject` class? it is never used.
Kinds regards,
SquareBoot

**Pull request merged**
